project:
    type: website
    output-dir: docs # GitHub Pages deploys from docs/
    render:
        - "*.qmd"

format:
    html:
        theme:
            light: flatly
            dark: darkly
        css: styles.css
        toc: True

website:
    draft-mode: visible

    navbar:
        left:
            - href: src/index.qmd
              text: Home
            - href: src/About-Me/about.qmd
              text: About Me
          
    page-footer:
        background: light
        border: True
        left: "Built with Quarto"
        center: Copyright © Aanish Pradhan 2025. All Right Reserved.
        right: 
            - icon: github
              href: https://github.com/aanish-pradhan/
            - icon: linkedin
              href: https://linkedin.com/in/aanishpradhan
            - icon: mortarboard-fill
              href: https://scholar.google.com/citations?user=h4lRh2oAAAAJ&hl=en

