project:
    type: website
    output-dir: docs
    render:
        - "*.qmd"
        
editor: source

format:
    html:
        theme: default
        
website:
    title: ""
    navbar:
        left:
            - href: src/index.qmd
              text: Home
