project:
    type: website
    output-dir: docs

format:
    html:
        theme:
            light: flatly
            dark: darkly
        css: styles.css
        # toc: true

website:
    title: "Aanish Pradhan"
    draft-mode: visible
    navbar:
        left:
            - href: src/Home/index.qmd
              text: "Home"
            - href: src/About-Me/about.qmd
              text: "About Me"
              
    page-footer:
        background: light
        border: true
        left: "Built with Quarto"
        center: "Copyright © Aanish Pradhan 2025. All Rights Reserved."
        right:
            - icon: github
              href: https://github.com/aanish-pradhan/
            - icon: linkedin
              href: https://linkedin.com/in/aanishpradhan





